apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejswebapp-deployment
  labels:
    app: nodejswebapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodejswebapp
  template:
    metadata:
      labels:
        app: nodejswebapp
    spec:
      containers:
      - name: nodejswebapp-container
        image: mxqeettasawaracr.azurecr.io/nodejswebapp:v1.0.0
        ports:
        

---
apiVersion: v1
kind: Service
metadata:
  name: nodesy-service
  labels:
    app: nodejswebapp
spec:
  selector:
    app: nodesy-app
  ports:
  - port: 3000
  type: LoadBalancer
